name: Nooda

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet requests

      - name: Build Windows App
        run: |
          flet pack main.py --name "JoyDose"

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE
          path: dist/

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet requests

      - name: Build APK
        run: |
          flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/apk/
