name: Nooda

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: windows
          - os: ubuntu-latest
            target: apk

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet requests

      - name: Build
        run: |
          flet build ${{ matrix.target }} nooda.py

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: build/
